# Site settings
title: Kristian Weegink
description: > # this means to ignore newlines until "baseurl:"
    My place on the internet dedicated to the accumulation of stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kristianweegink.com" # the base hostname & protocol for your site
github_username:  BuzzVII
name: Kristian Weegink

# Build settings
markdown: kramdown
