# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Hobby is Hobbies
description: > # this means to ignore newlines until "baseurl:"
    My place on the internet dedicated to the accumulation of hobbies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://BuzzVII.github.io" # the base hostname & protocol for your site
github_username:  BuzzVII
name: Kristian Weegink

# Build settings
markdown: kramdown
